FROM maven:3.9-eclipse-temurin-11 AS build
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:11-jre
COPY --from=build /target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]